name: My-GithubActions-basics

on:  
 push:
   branches: [main]
jobs:
  my-testing:    
    runs-on: ubuntu-latest     
    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello World from testing!"
      
  my-deploy:  
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello world from deploy job!"
     
