name: My-GithubActions-basics
env:
  APPLICATION_NAME   : "MyRxJs"
  DEPLOY_PACKAGE_NAME: "MyRxJs-deploy-ver-${{github.sha}}"

on:  
 push:
   branches: [main]
jobs:
  my-testing:    
    runs-on: ubuntu-latest     
    steps:
    
    - name: Print Hello Message in Testing
      run: echo "Hello World from testing!"
      
    - name: Execute few commands
      run: |
       echo "Hello Message1"
       echo "Hello Message2"
       echo "Application name is ${{ env.APPLICATION_NAME }}"
       
    - name: List current folder
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
      
  my-deploy:  
    runs-on: ubuntu-latest
    needs  : [my-testing]
    env:
      VAR1: "This is Job variable 1"
      VAR2: "This is Job variable 2"
     
    steps:
    
    - name: Print Hello Message in Deploy
      run : echo "Hello world from deploy job!"
      
    - name: Print env variables
      run : |
        echo "Var1 = ${{ env.VAR1 }}" 
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env: 
       LOCAL_VAR: "Super local variable"
      
    - name: Printing deployment package
      run: |      
       echo "Package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
       
    - name: Lets tests some packages if they are here
      run: aws --version
      
    - name: Lets tests some packages if they are here
      run: zip --version
     
