name: My-GithubActions-basics
env:
  APPLICATION_NAME   : "MyRxJs"
  DEPLOY_PACKAGE_NAME: "MyRxJs-deploy-ver-${{github.sha}}"

on:  
 push:
   branches: [main]
jobs:
  my-testing:    
    runs-on: ubuntu-latest     
    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello World from testing!"
    - name: Execute few commands
      run: |
       echo "Hello Message1"
       echo "Hello Message2"
       echo "Application name is ${{ env.APPLICATION_NAME }}"
    - name: List array folder
      run: ls-la
      
  my-deploy:  
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello world from deploy job!"
    - name: Printing deployment package
      run: |      
       echo "Package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
     
