name: My-GithubActions-basics

on:  
 push:
   branches: [main]
jobs:
  my-testing:    
    runs-on: ubuntu-latest     
    steps:
    - name: Print Hello Message
      run: echo print "Hello World from testing!"
      
  my-deploy:  
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo print "Hello world from deploy job!"
     
